<?php

namespace Bundle\ChessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

 class ChessRepository extends EntityRepository {

	/*public function getGameId() {
		$qb = $this -> createQueryBuilder('i') 
					-> select('*')
					-> from('game')
					-> where('gameid = '. $gameid);

		return $qb -> getQuery() -> getResult();
	}
*/	
	public function getGameboard($gameid) {
		$qb = $this -> createQueryBuilder('Game') 
					-> select('Game.gameboard')
					//-> from('Game','Game.gameboard')
					//-> where('Game.gameid = '. $gameid)
					;

		$result = $qb -> getQuery() -> getResult();
		$result = unserialize($result[0]['gameboard']);
		print_r($result);
		return $result;
	}

	public function updateGameboard($gameid,$gameboard) {
		$qb = $this -> createQueryBuilder('Game') 
					-> update('Game.gameboard', $gameboard)
					//-> from('Game','Game.gameboard')
					//-> where('Game.gameid = '. $gameid)
					;
		//$qb -> update('Game.gameboard', $gameboard);
		
	}

	public function getTurn() {
		$qb2 = $this -> createQueryBuilder('Game') 
					 -> select('Game.turn');
				//	-> from('game','turn');
					 

		$result = $qb2 -> getQuery() -> getSingleResult();
		$result = $result['turn'];
		//echo $result;
		return $result;
	}
}
