<?php

namespace Bundle\ChessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
	public function getGamesForPlayer($playerid)
    {
        $qb = $this->createQueryBuilder('Game')
                   ->select('Game')
                   ->where('Game.player1 = :player_id')
                   ->addOrderBy('Game.gameid')
                   ->setParameter('player_id', $playerid);

        return $qb->getQuery()
                  ->getResult();
    }
	
	public function getPlayer($playerid){
	    $qb = $this->createQueryBuilder('Player')
                   ->select('Player')
                   ->where('Player.playerid = :player_id')
                   ->setParameter('player_id', $playerid);

        return $qb->getQuery()
                  ->getResult();
		
	}

	public function getPlayerid() {
		$qb = $this -> createQueryBuilder('Player') 
					-> select('Player.playerid')
					-> getQuery() 
					;

		$result = $qb -> getResult();
		print_r($result);
		$result = count($result);
		return $result;
	}
	
}