<?php

namespace Bundle\ChessBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
	public function getPlayer($player){
	    $qb = $this->createQueryBuilder('Player')
                   ->select('Player')
                   ->where('Player.player = :player')
                   ->setParameter('player', $player)
				   ->getQuery();

        $result = $qb -> getResult();
		return $result[0];
	}


	public function checkNewPlayer($player){
	    $qb = $this->createQueryBuilder('Player')
                   ->select('Player')
                   ->where('Player.player = :player')
                   ->setParameter('player', $player)
				   ->getQuery();

        $result = $qb -> getResult();
		return $result[0];
		
	}
	
}