BundleChessBundle_homepage:
    pattern:  /
    defaults: { _controller: BundleChessBundle:Game:index }
    requirements:
        _method:  GET
        
        
BundleChessBundle_login_check:
    pattern: /login_check
    defaults: {_controller: BundleChessBundle:Player:login_check }
    requirements:
        _method: GET|POST

BundleChessBundle_newplayer:
    pattern:  /newplayer
    defaults: { _controller: BundleChessBundle:Player:newplayer }
    requirements:
        _method:  GET|POST

BundleChessBundle_loggedin:
    pattern:  /loggedin
    
    defaults: { _controller: BundleChessBundle:Player:loggedin }
    requirements:
        _method:  GET|POST

BundleChessBundle_game:
    pattern:  /game
    defaults: { _controller: BundleChessBundle:Game:game }
    requirements:
        _method:  GET|POST
        
BundleChessBundle_multiplayer:
    pattern:  /multiplayer
    defaults: { _controller: BundleChessBundle:Game:multiplayer }
    requirements:
        _method:  GET|POST

BundleChessBundle_move:
    pattern:  /move/{slug}
    defaults: { _controller: BundleChessBundle:Game:move}
    requirements:
        _method:  GET
        
BundleChessBundle_oldgame:
    pattern:  /oldgame/{slug}
    
    defaults: { _controller: BundleChessBundle:Game:oldGame }
    requirements:
        _method:  GET

BundleChessBundle_checkturn:
    pattern:  /checkturn
    defaults: { _controller: BundleChessBundle:Turn:checkturn }
    requirements:
        _method:  POST

BundleChessBundle_registernewplayer:
    pattern:  /registernewplayer
    defaults: { _controller: BundleChessBundle:Player:registernewplayer }
    requirements:
        _method:  GET|POST

BundleChessBundle_logout:
    pattern:  /logout/{player1}
    defaults: { _controller: BundleChessBundle:Player:logout}
    requirements:
        _method:  GET|POST


BundleChessBundle_waitforplayer:
    pattern:  /waitforplayer
    defaults: { _controller: BundleChessBundle:FindPlayer:waitforplayer }
    requirements:
        _method:  POST
