BundleChessBundle_homepage:
    pattern:  /
    defaults: { _controller: BundleChessBundle:Game:index }
    requirements:
        _method:  GET
        
        
BundleChessBundle_login_check:
    pattern: /login_check
    defaults: {_controller: BundleChessBundle:Player:login_check }
    requirements:
        _method: GET|POST

BundleChessBundle_newplayer:
    pattern:  /newplayer
    defaults: { _controller: BundleChessBundle:Player:newplayer }
    requirements:
        _method:  GET|POST

BundleChessBundle_loggedin:
    pattern:  /loggedin
    
    defaults: { _controller: BundleChessBundle:Player:loggedin }
    requirements:
        _method:  GET|POST

BundleChessBundle_game:
    pattern:  /game
    
    defaults: { _controller: BundleChessBundle:Game:game }
    requirements:
        _method:  GET|POST
        
BundleChessBundle_move:
    pattern:  /move/{slug}
    defaults: { _controller: BundleChessBundle:Game:move}
    requirements:
        _method:  GET
        
BundleChessBundle_oldgame:
    pattern:  /oldgame/{slug}
    
    defaults: { _controller: BundleChessBundle:Game:oldGame }
    requirements:
        _method:  GET

BundleChessBundle_checkturn:
    pattern:  /checkturn
    defaults: { _controller: BundleChessBundle:Turn:checkturn }
    requirements:
        _method:  POST
