BundleChessBundle_homepage:
    pattern:  /
    defaults: { _controller: BundleChessBundle:Game:index }
    requirements:
        _method:  GET

BundleChessBundle_game:
    pattern:  /game
    
    defaults: { _controller: BundleChessBundle:Game:game }
    requirements:
        _method:  GET|POST
        
BundleChessBundle_move:
    pattern:  /move/{slug}
    defaults: { _controller: BundleChessBundle:Game:move}
    requirements:
        _method:  GET
        
BundleChessBundle_oldgame:
    pattern:  /oldgame/{slug}
    
    defaults: { _controller: BundleChessBundle:Game:oldGame }
    requirements:
        _method:  GET
