BundleChessBundle_homepage:
    pattern:  /
    defaults: { _controller: BundleChessBundle:Game:index }
    requirements:
        _method:  GET

BundleChessBundle_game:
    pattern:  /game
    defaults: { _controller: BundleChessBundle:Game:game }
    requirements:
        _method:  GET
