parameters:
#    bundle_chess.example.class: Bundle\ChessBundle\Example

services:
#    bundle_chess.example:
#        class: %bundle_chess.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
